---
- name: Pull latest image and start container
  hosts: localhost
  gather_facts: false
  connection: ssh
  
  tasks:
    - name: Pull image
      community.docker.docker_compose_v2_pull:
         docker_host: tcp://
         policy: always
         #project_name:
         project_src: 
         tls: false
         validate_certs: false
