---
- name: Initial setup of linux servers
  hosts: initial_setup_server
  gather_facts: true
  become: yes
  become_method: sudo
  connection: ssh

  tasks:
    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Set timezone to Australia/Perth
      community.general.timezone:
        name: Australia/Perth

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ server_hostname }}" 

    - name: Change default password of existing user
      user:
        name: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
    
    - name: debug variables
      debug:
        msg:
          - "Variable 1: {{ ansible_user }}"
          - "Variable 2: {{ ansible_password }}"
          - "Variable 3: {{ server_hostname }}"