---
- name: Initial setup of linux servers
  hosts: single_server
  gather_facts: true
  become: yes
  become_method: sudo
  connection: ssh

  tasks:
    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        
    - name: Set timezone to Australia/Perth
      community.general.timezone:
        name: Australia/Perth
        
    - name: Perform a dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot_required_file

    - name: Reboot the server
      ansible.builtin.reboot:
        test_command: whoami
      when: reboot_required_file.stat.exists == true
      
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
