---
- name: Initial setup of linux servers
  hosts: wireguard
  gather_facts: true
  become: yes
  become_method: sudo
  connection: ssh

  tasks:
    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ path }}"
