---
- name: Initial setup of linux servers
  hosts: initial_setup_server
  gather_facts: true
  become: yes
  become_method: sudo
  connection: ssh

  tasks:
    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ lookup('env', 'update_hostname') }}" 

    - name: Set timezone to Australia/Perth
      community.general.timezone:
        name: Australia/Perth

    - name: Include initial setup tasks
      include_tasks: "{{ item }}"
      loop:
        - common_tasks/task_apt_update_upgrade.yml
        - common_tasks/task_install_docker_engine.yml

    - name: Change default password
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        password: "{{ lookup('env', 'update_password') }}"
        update_password: always