---
- name: Initial setup of linux servers
  hosts: initial_setup_server
  gather_facts: true
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
    - include_playbook: update_linux_servers.yml

  tasks:
    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Set timezone to Australia/Perth
      community.general.timezone:
        name: Australia/Perth
