---
- name: Initial setup of linux servers
  hosts: single_server
  gather_facts: true
  become: yes
  become_method: sudo
  connection: ssh

  tasks:
    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        
    - name: Set timezone to Asia/Tokyo
      community.general.timezone:
        name: Asia/Tokyo
