---
- name: Install public key on remote machine
  hosts: wireguardserver
  gather_facts: true
  become: true
  become_method: sudo
  connection: ssh
  
  tasks:
   - name: Set authorized key for remote user
     ansible.posix.authorized_key:
      user: "{{ ubtuser }}"
      state: present
