---
- name: Update linux servers
  hosts: linux_servers
  gather_facts: true
  become: true
  become_method: sudo
  connection: ssh
  serial: 2

  tasks:
    - name: Perform a dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot_required_file
      register: reboot_required_file

    - name: Reboot the server
      ansible.builtin.reboot:
        pre_reboot_delay: 5
        #post_boot_delay: 5
        test_command: whoami
      when: reboot_required_file.stat.exists == true
      
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
