---
- name: Update linux servers
  hosts: linux_servers
  gather_facts: true
  become: true
  become_method: sudo
  connection: ssh
  serial: 2

  tasks:
    - name: Include initial setup tasks
      include_tasks: common_tasks/tasks_apt_update_upgrade.yml
