---
- name: Update existing docker containers to latest image
  hosts: ubtserver_networkmgmt
  gather_facts: false
  connection: ssh
  become: true
  vars_files:
    - compose_paths

  tasks:
    - name: Pull and start latest docker images
      community.docker.docker_compose_v2:
        project_src: "{{ item }}"
        pull: always
        state: present
      register: output
      loop: "{{ vars }}"    

    - name: Show results of starting services
      ansible.builtin.debug:
        var: output
